server:
  port: 8080

  
eureka:
  client:
    serviceUrl:
      deaultZone: http://localhost:8761:/eureka/
      
      
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/indiantrait
    username: root
    password: manager
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: indiantrait@gmail.com
    password: zgfelnhtbbckxyxa
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#  security:
#    oauth2:
#      client:
#        registration:
#          myoauth2:
#            provider: spring
#            client-id: client
#            client-secret: secret
#            authorization-grant-type: authorization_code
#            redirect-uri: http://127.0.0.1:8080/login/oauth2/code/myoauth2
#            scope: openid
#        provider:
#         spring:
#            issuer-uri: http://localhost:9000
  boot:
    admin:
      client:
        instance:
          management-base-url: http://localhost:8080    
            
            
management:
 tracing:
  sampling:
   probablity: 1.0