# Generated by Django 4.2 on 2024-04-08 07:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_message"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"ordering": ["created"]},
        ),
    ]
