server:
  port: 8088

  
  
spring: 
  profiles:
    active: native
  application:
    name: config-server
            
            
            
#eureka:
#  client:
#    serviceUrl:
#      deaultZone: http://localhost:8761:/eureka/
