# Generated by Django 5.0.3 on 2024-03-30 02:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="projects",
            new_name="Project",
        ),
    ]
