# Generated by Django 5.0.3 on 2024-03-31 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_project_featured_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="author",
            field=models.CharField(default="Anonymous", max_length=200),
        ),
    ]
