# Generated by Django 5.0.3 on 2024-03-31 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_project_author"),
        ("users", "0002_profile_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="author",
        ),
        migrations.AddField(
            model_name="project",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.profile",
            ),
        ),
    ]
